packages:
  - artifacts/portfolio

autoInstallPeers: false

onlyBuiltDependencies:
  - esbuild

overrides:
  '@rollup/rollup-darwin-arm64': '*'
  lightningcss-darwin-arm64: '*'
  '@tailwindcss/oxide-darwin-arm64': '*'